@baseUrl = http://localhost:3001

@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTkzNjMxMjY3LCJleHAiOjE1OTM2MzMwNjd9.Qf_cG0u85Jkn441jH9KpMQRZrqtJDNUl5xkWzv8b1zg

### Create an Account

POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "email": "lbc92@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678"
}

### Sign In

POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
    "email": "lbc92@gmail.com",
    "password": "12345678"
}

### List Links

GET {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### Get a Link by Id

GET {{baseUrl}}/link/3
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### Create Link

POST {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "label": "Facebook",
    "url": "https://facebook.com",
    "isSocial": false
}


### Update a Link

PUT {{baseUrl}}/link/4
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "label": "Facebook Brazil",
    "url": "https://facebook.com.br"
}

### Delete a Link
DELETE {{baseUrl}}/link/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
