@baseUrl = http://localhost:3001

@contentType = application/json

### Test Get

GET {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "email": "lbc93@hotmail.com",
    "password": "12345678"
}

### Create an Account

POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "email": "lbc92@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678"
}